FROM continuumio/miniconda:4.7.12
RUN mkdir -p /code
RUN mkdir -p /data/processing
COPY event_detector /code/event_detector
WORKDIR /code/event_detector
RUN conda update -n base -c defaults conda
RUN conda env create --file environment.yml

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "gtm", "/bin/bash", "-c"]

RUN python download_wordnet.py