name: gtm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - python-dotenv
  # - jupyter
  - pip
  - pip:
    - numpy
    - pandas
    - scikit-learn==0.23.2
    - nltk==3.5
    - gensim==3.8.3
    - sqlalchemy==1.3.18
    - sqlalchemy-utils
    - colorama==0.4.3
    - tika==1.24
    - apscheduler
    - fasttext==0.9.2
    - tweepy
  - geopandas=0.8.1
  - pycountry=20.7.3
  # - pyproj=2.6.1
  - shapely=1.7.0
  - geoalchemy2
  - psycopg2
  - setuptools~=49.3.1
  - pymorphy2==0.8
  - pymorphy2-dicts
  - descartes
  - pyjanitor
  - spacy=2.3.2
  - spacy-lookups-data

