name: gtm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - python-dotenv
  - pip
  - pip:
    - numpy==1.19.0
    - pandas
    - scipy==1.5.2
    - scikit-learn==0.23.2
    # - spacy==2.3.2
    # - spacy-lookups-data
    - nltk==3.5
    - gensim==3.8.3
    - wordcloud==1.7.0
    - sqlalchemy==1.3.18
    - sqlalchemy-utils
    - colorama==0.4.3
    - tika==1.24
    - transformers
    - cython
    - sentence_transformers
    - tqdm
    - apscheduler
  - geopandas=0.8.1
  - basemap
  - basemap-data-hires
  - pycountry=20.7.3
  - pyproj=2.6.1
  - shapely=1.7.0
  - owslib=0.20.0
  - geoalchemy2
  - psycopg2
  - matplotlib
  - setuptools~=49.3.1
  - pymorphy2==0.8
  - pymorphy2-dicts
  - descartes
  - pyjanitor
  - spacy=2.3.2
  - spacy-lookups-data

